import type { Task } from '../types/agent';

/**
 * Extended task interface for structured planning.
 */
export interface StructuredTask extends Task {
  tool: string;
  dependencies: string[];
}

/**
 * Structured plan interface generated by the LLM.
 */
export interface StructuredPlan {
  id: string;
  goal: string;
  reasoning: string;
  tasks: StructuredTask[];
  createdAt: number;
}

/**
 * Schema definition for the Plan (used for LLM guidance).
 */
export const PlanSchema = {
  type: 'object',
  properties: {
    id: { type: 'string' },
    goal: { type: 'string' },
    reasoning: { type: 'string' },
    tasks: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          description: { type: 'string' },
          tool: { type: 'string' },
          dependencies: {
            type: 'array',
            items: { type: 'string' }
          },
          metadata: { type: 'object' }
        },
        required: ['id', 'description', 'tool', 'dependencies']
      }
    }
  },
  required: ['id', 'goal', 'reasoning', 'tasks']
};
